services:
  - type: web
    name: luxury-loop
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: ACCESS_TOKEN_EXPIRY
        value: 1d
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_EXPIRY
        value: 10d
